// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJom2MR8y_Xr2wXQocAZwnce3krpaCJqE',
    appId: '1:85988987684:web:65b45b00d3b6d4f79319b1',
    messagingSenderId: '85988987684',
    projectId: 'schoolcontributionsapp',
    authDomain: 'schoolcontributionsapp.firebaseapp.com',
    storageBucket: 'schoolcontributionsapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAueMgeVjJNc-B_17VW8tUDrRqOagsH-Nc',
    appId: '1:85988987684:android:fb90578cdc6e74649319b1',
    messagingSenderId: '85988987684',
    projectId: 'schoolcontributionsapp',
    storageBucket: 'schoolcontributionsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRCHrHgqGLXy1FgPrejZeZPAXJ8OvDnTs',
    appId: '1:85988987684:ios:0b2614d646e7fa469319b1',
    messagingSenderId: '85988987684',
    projectId: 'schoolcontributionsapp',
    storageBucket: 'schoolcontributionsapp.firebasestorage.app',
    iosBundleId: 'com.example.schoolContributionsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRCHrHgqGLXy1FgPrejZeZPAXJ8OvDnTs',
    appId: '1:85988987684:ios:0b2614d646e7fa469319b1',
    messagingSenderId: '85988987684',
    projectId: 'schoolcontributionsapp',
    storageBucket: 'schoolcontributionsapp.firebasestorage.app',
    iosBundleId: 'com.example.schoolContributionsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJom2MR8y_Xr2wXQocAZwnce3krpaCJqE',
    appId: '1:85988987684:web:03e7adec4409c68e9319b1',
    messagingSenderId: '85988987684',
    projectId: 'schoolcontributionsapp',
    authDomain: 'schoolcontributionsapp.firebaseapp.com',
    storageBucket: 'schoolcontributionsapp.firebasestorage.app',
  );
}
